# -*- coding: utf-8 -*-
"""Rock,Paper,Scissor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vZlNI5m-_oK-domGoNF_I3DeuFvtVI7F
"""

import random
options = ["Rock", "Paper", "Scissor"]
computer = random.choice(options)
player = False
computer_score = 0
player_score = 0
while True:
    player = input("Rock, Paper or  Scissor?").capitalize()
    ## Conditions
    if player == computer:
        print("Tie!")
    elif player == "Rock":
        if computer == "Paper":
            print("You lost....", computer, "folds", player)
            computer_score+=1
        else:
            print("You won!!", player, "smashes", computer)
            player_score+=1
    elif player == "Paper":
        if computer == "Scissor":
            print("You lost....", computer, "cuts", player)
            computer_score+=1
        else:
            print("You won!!", player, "covers", computer)
            player_score+=1
    elif player == "Scissor":
        if computer == "Rock":
            print("You lost....", computer, "smashes", player)
            computer_score+=1
        else:
            print("You won!!", player, "cuts", computer)
            player_score+=1
    elif player=='End':
        print("Final Scores:")
        print(f"COMPUTER:{computer_score}")
        print(f"PLAYER:{player_score}")
        break

